// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOU7nqOXoqbpL7McKz3lFczyeygRREmc',
    appId: '1:53211156869:web:3e299fddfc637130ae34ec',
    messagingSenderId: '53211156869',
    projectId: 'gdsc-9141d',
    authDomain: 'gdsc-9141d.firebaseapp.com',
    storageBucket: 'gdsc-9141d.appspot.com',
    measurementId: 'G-LE5SY5MKX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjIjUAxmQJAl6TABKBUBGEZ3k69HC4I54',
    appId: '1:53211156869:android:e8f2eecd3c32ff9bae34ec',
    messagingSenderId: '53211156869',
    projectId: 'gdsc-9141d',
    storageBucket: 'gdsc-9141d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZpUzD4aMC83pYplCamkMyvw8uW5PHc4A',
    appId: '1:53211156869:ios:59ad69ddeacfeac1ae34ec',
    messagingSenderId: '53211156869',
    projectId: 'gdsc-9141d',
    storageBucket: 'gdsc-9141d.appspot.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpUzD4aMC83pYplCamkMyvw8uW5PHc4A',
    appId: '1:53211156869:ios:c48f46a85c84ae61ae34ec',
    messagingSenderId: '53211156869',
    projectId: 'gdsc-9141d',
    storageBucket: 'gdsc-9141d.appspot.com',
    iosBundleId: 'com.example.gdsc.RunnerTests',
  );
}
